### ISSUE TITLE
Dog fooding

### ISSUE THREAD

**Issue by mariusor** [mariusor/littr.go#2]
Basically this means to move all the frontend functionality to use ActivityPub API calls to our own api/ end-points.

- [x] Index - Load Top Level Items  #3 
- [x] Domain/User - Load All Items with conditions #4 
- [x] Item - Load Item and all its children #5
- [x] Likes - Load likes/dislikes  #11 

- [x] Item Actions: New Item - Create Activity Pub Item as Current Account #13
- [x] Item Actions: Like/Dislike - Create a new Like/Dislike activity for Item #12 
- [x] Item Actions: Edit/Delete - Allow Current Account to perform actions on Item #17

- [ ] ~Load Current Account  - Load all interesting information about current account~ #16 
- [ ] ~Login - no idea yet how this can be done using ActivityPub~ 
- [ ] ~Register - no idea yet how this can be done using ActivityPub~

**Comment by mariusor** [comment]
All the important parts of this ticket have been closed. 

The result is that the frontend can perform all actions that can be done on an item to be done through ActivityPub operations.
